/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductByIdResponse } from '../../models/product-by-id-response';

export interface FindProductById$Params {
  'product-id': string;
}

export function findProductById(http: HttpClient, rootUrl: string, params: FindProductById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductByIdResponse>> {
  const rb = new RequestBuilder(rootUrl, findProductById.PATH, 'get');
  if (params) {
    rb.path('product-id', params['product-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductByIdResponse>;
    })
  );
}

findProductById.PATH = '/{product-id}';
