/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UploadsService } from './services/uploads.service';
export { AuthenticationService } from './services/authentication.service';
export { ProductService } from './services/product.service';
