services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: supareel_dev_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5435:5432
    networks:
      - supareel-docker-net
    restart: unless-stopped
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:25.0.6
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - supareel-docker-net
    command:
      - "start-dev"
networks:
  supareel-docker-net:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local