/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
export interface Attachment {
  createdBy?: string;
  createdDate?: string;
  fileName?: string;
  fileSize?: number;
  fileUrl?: string;
  id?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  product?: Product;
}
