/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateProductRequest {
  currency: 'USD' | 'EUR' | 'INR';
  description?: string;
  id?: string;
  price: number;
  title: string;
  user_id: string;
}
