/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageResponse {
  message?: string;
  status?: 'SUCCESS' | 'ERROR' | 'INFO' | 'WARNING';
}
