/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentGateway } from '../models/payment-gateway';
import { Product } from '../models/product';
import { User } from '../models/user';
export interface Order {
  buyer?: User;
  createdAt?: string;
  id?: string;
  paymentGatewayId?: PaymentGateway;
  product?: Product;
  quantity?: number;
  status?: 'PENDING' | 'COMPLETED' | 'FAILED';
  totalAmount?: number;
  updatedAt?: string;
}
