/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductByIdResponse } from '../models/product-by-id-response';
export interface PageResponseProductByIdResponse {
  first?: boolean;
  last?: boolean;
  list?: Array<ProductByIdResponse>;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
