/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Attachment } from '../models/attachment';
import { Order } from '../models/order';
import { User } from '../models/user';
export interface Product {
  createdBy?: string;
  createdDate?: string;
  currency?: 'USD' | 'EUR' | 'INR';
  description?: string;
  files?: Array<Attachment>;
  id?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  orders?: Array<Order>;
  owner?: User;
  price?: number;
  title?: string;
}
