/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Attachment } from '../models/attachment';
import { Order } from '../models/order';
import { User } from '../models/user';
export interface ProductByIdResponse {
  currency?: 'USD' | 'EUR' | 'INR';
  description?: string;
  files?: Array<Attachment>;
  id?: string;
  orders?: Array<Order>;
  price?: number;
  title?: string;
  user?: User;
}
