/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Role {
  createdBy?: string;
  createdDate?: string;
  id?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  name?: string;
}
