/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
import { Order } from '../models/order';
import { Product } from '../models/product';
import { Role } from '../models/role';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  dateOfBirth?: string;
  email?: string;
  enabled?: boolean;
  firstName?: string;
  fullName?: string;
  id?: string;
  lastModifiedDate?: string;
  lastName?: string;
  name?: string;
  orders?: Array<Order>;
  password?: string;
  products?: Array<Product>;
  roles?: Array<Role>;
  username?: string;
}
